/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fictionalUni;

import java.util.ArrayList;

import org.joda.time.DateTime;

import uniutils.*;

public class mainUni {
    public String getGreeting() {
        return "hello!";
    }

    public static void main(String[] args) {
        Course BCS = new Course("BCS", new DateTime(2022, 9, 1, 8, 0), new DateTime(2023, 4, 1, 8, 0));
        
        ArrayList<uniutils.Module> modules = new ArrayList<uniutils.Module>();
        modules.add(new uniutils.Module("programming", "BCS001", new Lecturer()));
        modules.add(new uniutils.Module("professionalSkills", "BCS001", new Lecturer()));
        modules.add(new uniutils.Module("databases", "BCS001", new Lecturer()));

        for(uniutils.Module module : modules) {
            BCS.addModule(module);
        }
        
        ArrayList<Student> students = new ArrayList<Student>();
        students.add(new Student("John", 22, new DateTime(2000, 1, 1, 8, 0), 000, BCS));
        students.add(new Student("Eiofa", 23, new DateTime(1999, 1, 1, 8, 0), 000, BCS));
        students.add(new Student("Cian", 24, new DateTime(1998, 1, 1, 8, 0), 000, BCS));
        students.add(new Student("Molly", 25, new DateTime(1997, 1, 1, 8, 0), 000, BCS));
        students.add(new Student("Trevor", 26, new DateTime(1996, 1, 1, 8, 0), 000, BCS));
        
        for(Student student : students) {
            BCS.addStudent(student);
        }


        //print everything for assignment.
        System.out.println(BCS);
    }
}
